# Generated by Django 4.0.10 on 2023-08-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_les4', '0006_alter_advertisement_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='дата последнего обновления'),
        ),
    ]
