# Generated by Django 4.0.10 on 2023-08-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_les4', '0007_alter_advertisement_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
